config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  root 'games#index'
  resources :questions
  resources :games
  resources :listings

  devise_scope :user do
    post 'sessions' => 'sessions#create', :as => 'login'
  end

  namespace :api do
    namespace :v1 do
      resources :guesses
      resources :users
      resources :questions
      resources :answers
      resources :games
      resources :games do
        post 'join_game' => 'games#join_game', :as => 'join_game'
      end
    end
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |listing|
        csv << listing.attributes.values_at(*column_names)
      end
    end
  end

  def get_details(mls_num,vendor)
    @vendor = vendor

    response = HTTParty.get("https://rets.io/api/v1/#{vendor}/listings?access_token=#{ENV['server_token']}&radius=30&mlsListingID=#{mls_num}")
    response = response.to_hash['bundle']

    chosen_listing = response.first
    @hood_name = chosen_listing['subdivision']
    @chosen_mls_num = chosen_listing['mlsListingID']
    @image_url = chosen_listing['media'].first['url']
    @price = chosen_listing['price']
    @address = chosen_listing['address']
    @dom = chosen_listing['daysOnMarket']
    @beds = chosen_listing['bedrooms']
    @baths = chosen_listing['baths']

    #agent info:
    # @agent_code = chosen_listing['mlsAgentID']
    #
    # agent_response = HTTParty.get("https://rets.io/api/v1/#{vendor}/agents?access_token=#{ENV['server_token']}&mlsAgentID=#{@agent_code}")
    # agent_response = agent_response.to_hash['bundle']
    #
    # chosen_agent = agent_response.first
    # @agent_name = chosen_agent['fullName']
    # @agent_cell = chosen_agent['cellPhone']

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  def index
    @listings = Listing.all
    respond_to do |format|
      format.html
      format.csv { send_data @listings.to_csv }
      #format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  # GET /listings/1
  def show
    @listing = Listing.find(params[:id])
    get_details(@listing.mls_num, "armls")
  end

  def get_details(mls_num,vendor)
    @vendor = vendor

    response = HTTParty.get("https://rets.io/api/v1/#{vendor}/listings?access_token=#{ENV['server_token']}&radius=30&mlsListingID=#{mls_num}")
    response = response.to_hash['bundle']

    chosen_listing = response.first
    @hood_name = chosen_listing['subdivision']
    @chosen_mls_num = chosen_listing['mlsListingID']
    @image_url = chosen_listing['media'].first['url']
    @price = chosen_listing['price']
    @address = chosen_listing['address']
    @dom = chosen_listing['daysOnMarket']
    @beds = chosen_listing['bedrooms']
    @baths = chosen_listing['baths']

    #agent info:
    # @agent_code = chosen_listing['mlsAgentID']
    #
    # agent_response = HTTParty.get("https://rets.io/api/v1/#{vendor}/agents?access_token=#{ENV['server_token']}&mlsAgentID=#{@agent_code}")
    # agent_response = agent_response.to_hash['bundle']
    #
    # chosen_agent = agent_response.first
    # @agent_name = chosen_agent['fullName']
    # @agent_cell = chosen_agent['cellPhone']

  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to @listing, notice: 'Listing was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /listings/1
  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /listings/1
  def destroy
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def listing_params
      params[:listing]
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings Judged</h1>

<table class="table table-bordered table-hover" bgcolor="#fff">
  <thead>
    <tr>
      <th><b>MLS Number</b></th>
      <th><b>Over Priced</b></th>
      <th><b>Under Priced</b></th>
      <th><b>Hot Look</b></th>
      <th><b>Actions</b></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.mls_num %></td>
        <td><%= listing.list_price_over %></td>
        <td><%= listing.list_price_under %></td>
        <td><%= listing.recognizable %></td>
        <td><%= link_to('Show', listing, :class => "btn btn-primary") %>
        <%# link_to 'Edit', edit_listing_path(listing) %>
        <%# link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Download to CSV", listings_path(format: "csv"), :class => "btn btn-primary" %>
<div class="col-md-12 text-center">
  <ul class="pagination pagination-lg pager" id="myPager"></ul>
</div>
<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class=col-md-6>
  <div class="jumbotron">
    <%= image_tag("#{@image_url}", size:"470x300") %>

  </div>

</div>

<div class=col-md-6>
  <h3><%= @address %></h3>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td>Address:</td>
          <td><%= @address %></td>
        </tr>
        <tr>
          <td>Price</td>
          <td><%= @price %></td>
        </tr>
        <tr>
          <td>Beds</td>
          <td><%= @beds %></td>
        </tr>
        <tr>
          <td>Baths</td>
          <td><%= @baths %></td>
        </tr>
        <tr>
          <td>Number of Overpriced Votes</td>
          <td class="danger"><%= @listing.list_price_over %></td>
        </tr>
        <tr>
          <td>Number of Underpriced Votes</td>
          <td class="success"><%= @listing.list_price_under %></td>
        </tr>
        <tr>
          <td>Number of Trendy Votes</td>
          <td class="success"><%= @listing.recognizable %></td>
        </tr>

    </tbody>
  </table>
</div>