config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  root 'games#index'
  resources :questions
  resources :games
  resources :listings

  devise_scope :user do
    post 'sessions' => 'sessions#create', :as => 'login'
  end

  namespace :api do
    namespace :v1 do
      resources :guesses
      resources :users
      resources :questions
      resources :answers
      resources :games
      resources :games do
        post 'join_game' => 'games#join_game', :as => 'join_game'
      end
    end
  end

end

app/controllers/api/v1/guesses_controller.rb
class Api::V1::GuessesController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    p params
    answer = Answer.find(params[:answer_id])
    @guess = Guess.new(answer_id:params[:answer_id], user_id:params[:user_id], question_id:answer.question_id)
    p @guess

    if @guess.save
      render json: {success:true, result:@guess}

      # update the valuable feedback data
      mls_num = @guess.answer.mls_num
      p "MLS NUM IS #{mls_num}"
      question_num = @guess.answer.question.quest_num
      p "Question NUM IS #{question_num}"

      if Listing.where(mls_num:mls_num).count >= 1
        @listing = Listing.where(mls_num:mls_num).last
        if question_num == 1
          count = @listing.recognizable
          count = count + 1
          @listing.update(recognizable:count)
        elsif question_num == 2
          count = @listing.list_price_under
          count = count + 1
          @listing.update(list_price_under:count)
          Guess.where(answer_id:@guess.answer.id).each do |guess|
            unless guess.id == @guess.id
              if listing = Listing.where(mls_num:guess.mls_num).count >= 1
                count = @listing.list_price_over
                count = count + 1
                listing.update(list_price_over:count)
              else
                Listing.create!(mls_num:guess.mls_num, list_price_over:1)
              end # if
            end # unless
          end # Guess.where
        end # if question_num
      else
        @listing = Listing.create!(mls_num:mls_num)
        if question_num == 1
          count = @listing.recognizable
          count = count + 1
          @listing.update(recognizable:count)
        elsif
          count = @listing.list_price_under
          count = count + 1
          @listing.update(list_price_under:count)
          Guess.where(answer_id:@guess.answer.id).each do |guess|
            unless guess.id == @guess.id
              if listing = Listing.where(mls_num:guess.mls_num).count >= 1
                count = @listing.list_price_over
                count = count + 1
                listing.update(list_price_over:count)
              else
                Listing.create!(mls_num:guess.mls_num, list_price_over:1)
              end # if
            end # unless
          end # Guess.where
        end
      end # if Listing.where

    else
      render json: {success:true, result:@guess}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess
      @guess = Guess.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def guess_params
      params.permit(:answer_id, :user_id, :question_id)
    end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_guess, only: [:show, :edit, :update, :destroy]

  # GET /guesses
  def index
    @guesses = Guess.all
  end

  # GET /guesses/1
  def show
  end

  # GET /guesses/new
  def new
    @guess = Guess.new
  end

  # GET /guesses/1/edit
  def edit
  end

  # POST /guesses
  def create
    @guess = Guess.new(guess_params)


    if @guess.save

      redirect_to @guess, notice: 'Guess was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /guesses/1
  def update
    if @guess.update(guess_params)
      redirect_to @guess, notice: 'Guess was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /guesses/1
  def destroy
    @guess.destroy
    redirect_to guesses_url, notice: 'Guess was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess
      @guess = Guess.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def guess_params
      params.permit(:answer_id, :user_id, :question_id)
    end
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/views/guesses/_form.html.erb
<%= form_for(@guess) do |f| %>
  <% if @guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guess.errors.count, "error") %> prohibited this guess from being saved:</h2>

      <ul>
      <% @guess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guesses/edit.html.erb
<h1>Editing Guess</h1>

<%= render 'form' %>

<%= link_to 'Show', @guess %> |
<%= link_to 'Back', guesses_path %>

app/views/guesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guesses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guesses.each do |guess| %>
      <tr>
        <td><%= link_to 'Show', guess %></td>
        <td><%= link_to 'Edit', edit_guess_path(guess) %></td>
        <td><%= link_to 'Destroy', guess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guess', new_guess_path %>

app/views/guesses/new.html.erb
<h1>New Guess</h1>

<%= render 'form' %>

<%= link_to 'Back', guesses_path %>

app/views/guesses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_guess_path(@guess) %> |
<%= link_to 'Back', guesses_path %>